#if !canImport(ObjectiveC)
import XCTest

extension ProcedureTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProcedureTests = [
        ("testChaining", testChaining),
        ("testFinally", testFinally),
        ("testTreeDependency", testTreeDependency),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ProcedureTests.__allTests__ProcedureTests),
    ]
}
#endif
